const books = [
  {
    title: "Atomic Habits",
    author: "James Clear",
    price: "Rp 89.000",
    genre: "Self-Help",
    img: "https://nlink.at/KpRR",
    rating: "★★★★★",
  },
  {
    title: "Rich Dad Poor Dad",
    author: "Henry Manampiring",
    price: "Rp 75.000",
    genre: "Self Improvement",
    img: "https://nlink.at/aYnq",
    rating: "★★★★★",
  },
  {
    title: "The Psychology of Money",
    author: "Morgan Housel",
    price: "Rp 82.000",
    genre: "Finansial",
    img: "https://nlink.at/cPLG",
    rating: "★★★★☆",
  },
  {
    title: "Laut Bercerita",
    author: "Leila S. Chudori",
    price: "Rp 68.000",
    genre: "Self-Help",
    img: "https://nlink.at/KfUH",
    rating: "★★★★★",
  },
  {
    title: "Sebuah Seni untuk Bersikap Bodo Amat",
    author: "Mark Manson",
    price: "Rp 72.000",
    genre: "Self-development",
    img: "https://nlink.at/jYq2",
    rating: "★★★★★",
  },
  {
    title: "Sapiens",
    author: "Yuval Noah Harari",
    price: "Rp 115.000",
    genre: "Sejarah",
    img: "https://nlink.at/gBCr",
    rating: "★★★★☆",
  },
  {
    title: "Start With Why",
    author: "Simon Sinek",
    price: "Rp 79.000",
    genre: "Bisnis",
    img: "https://nlink.at/jms5",
    rating: "★★★★★",
  },
  {
    title: "Bumi Manusia",
    author: "Pramudya Ananta Toer",
    price: "Rp 85.000",
    genre: "Sejarah",
    img: "https://nlink.at/35xF",
    rating: "★★★★☆",
  },
  {
    title: "Dune",
    author: "Frank Herbert",
    price: "Rp 130.000",
    genre: "Sci-Fi",
    img: "https://nlink.at/qJY6",
    rating: "★★★★★",
  },
  {
    title: "Langit Mengambil",
    author: "Ika Natassa",
    price: "Rp 89.000",
    genre: "Romansa",
    img: "https://surl.li/lflchx",
    rating: "★★★★★",
  },
  {
    title: "Timun Jelita",
    author: "Raditya Dika",
    price: "Rp 85.000",
    genre: "Fiksi",
    img: "https://surl.lu/uovhvq",
    rating: "★★★★☆",
  },
  {
    title: "Hidup Ini Terlalu Banyak Kamu",
    author: "Pidi Baiq",
    price: "Rp 72.000",
    genre: "Puisi",
    img: "https://surl.li/whjsro",
    rating: "★★★★★",
  },
];

export default books;
